import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header"; 
import { Footer } from "./components/footer"; 

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJS 26 WordPress GraphQL Starter",
  description: "Generated by JTSD MEDIA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="page max-w-[780px] p-4 md:p-10 mx-auto bg- min-h-screen">
          <Header />  
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
